//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockDiagramCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class languagepl_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal languagepl_PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockDiagramCreator.languagepl-PL", typeof(languagepl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok decyzyjny.
        /// </summary>
        internal static string DecideBlock {
            get {
                return ResourceManager.GetString("DecideBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram posiada już blok startowy.
        /// </summary>
        internal static string DoubleStartBlockWarning {
            get {
                return ResourceManager.GetString("DoubleStartBlockWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odczyt zakończony niepowidzeniem.
        /// </summary>
        internal static string LoadFail {
            get {
                return ResourceManager.GetString("LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odczyt udany.
        /// </summary>
        internal static string LoadSucces {
            get {
                return ResourceManager.GetString("LoadSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok operacyjny.
        /// </summary>
        internal static string OperationBlock {
            get {
                return ResourceManager.GetString("OperationBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis nieudany.
        /// </summary>
        internal static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis udany.
        /// </summary>
        internal static string SaveSucces {
            get {
                return ResourceManager.GetString("SaveSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartBlock {
            get {
                return ResourceManager.GetString("StartBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopBlock {
            get {
                return ResourceManager.GetString("StopBlock", resourceCulture);
            }
        }
    }
}
